[package]
name = "guildly"
version = "0.1.0"
cairo-version = "2.2.0"

[dependencies]
starknet = ">=2.2.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.2" }

[[target.starknet-contract]]
build-external-contracts = [
    "openzeppelin::token::erc20::erc20::ERC20", 
    "openzeppelin::token::erc721::erc721::ERC721"
]
sierra = true
casm = false

[scripts]
test = "snforge"

[tool.snforge]
#exit_first = true
