["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "./lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src", "./lib/realms_contracts"]
stdout-on-success = true

["protostar.build"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.test"]
disable-hint-validation = true